"""create_procurement_tables

Revision ID: 269df76f8314
Revises: 29045c074056
Create Date: 2026-07-15 04:31:06.944060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269df76f8314'
down_revision: Union[str, Sequence[str], None] = '29045c074056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex_rates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('manual_override_rate', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_rates_from_currency'), 'forex_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_forex_rates_id'), 'forex_rates', ['id'], unique=False)
    op.create_index(op.f('ix_forex_rates_to_currency'), 'forex_rates', ['to_currency'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('china_domestic_shipping', sa.Float(), nullable=False),
    sa.Column('international_freight', sa.Float(), nullable=False),
    sa.Column('customs_duty_percent', sa.Float(), nullable=False),
    sa.Column('clearing_charges', sa.Float(), nullable=False),
    sa.Column('insurance', sa.Float(), nullable=False),
    sa.Column('other_charges', sa.Float(), nullable=False),
    sa.Column('total_landed_cost_inr', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_number'), 'purchase_orders', ['po_number'], unique=True)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('purchase_order_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_foreign', sa.Float(), nullable=False),
    sa.Column('landed_cost_inr_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_id'), 'purchase_order_items', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_order_items_sku'), 'purchase_order_items', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_items_sku'), table_name='purchase_order_items')
    op.drop_index(op.f('ix_purchase_order_items_id'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_purchase_orders_po_number'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_forex_rates_to_currency'), table_name='forex_rates')
    op.drop_index(op.f('ix_forex_rates_id'), table_name='forex_rates')
    op.drop_index(op.f('ix_forex_rates_from_currency'), table_name='forex_rates')
    op.drop_table('forex_rates')
    # ### end Alembic commands ###
