"""create_pricing_tables

Revision ID: e2ae0c681a74
Revises: 9401f9fdff6f
Create Date: 2026-07-15 04:49:24.507697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ae0c681a74'
down_revision: Union[str, Sequence[str], None] = '9401f9fdff6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_fee_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('referral_fee_percent', sa.Float(), nullable=False),
    sa.Column('fixed_closing_fee', sa.Float(), nullable=False),
    sa.Column('weight_handling_fee', sa.Float(), nullable=False),
    sa.Column('other_fees', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_fee_templates_channel_name'), 'channel_fee_templates', ['channel_name'], unique=True)
    op.create_index(op.f('ix_channel_fee_templates_id'), 'channel_fee_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_fee_templates_id'), table_name='channel_fee_templates')
    op.drop_index(op.f('ix_channel_fee_templates_channel_name'), table_name='channel_fee_templates')
    op.drop_table('channel_fee_templates')
    # ### end Alembic commands ###
